# SVM-digit-recognizer

In [2]:
import numpy as np
import pandas as pd
import operator

## import train_data, train_labels, test_data

In [3]:
train=r'C:\Users\Lenovo\codes\digit-recognizer\input\train.csv'
train_set=pd.read_csv(train)
train_set

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [4]:
train_labels=train_set.iloc[:,0]
train_labels

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [5]:
train_data=train_set.iloc[:,1:]
train_data

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995       0       0       0       0       0       0       0       0       0   
41996       0       0       0       0       0       0       0       0       0   
41997       0       0       0       0       0       0       0       0       0   
41998       0       0       0       0       0       0       0       0       0   
41999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 784 columns]

In [6]:
test=r'C:\Users\Lenovo\codes\digit-recognizer\input\test.csv'
test_data=pd.read_csv(test)
test_data

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27995       0       0       0       0       0       0       0       0       0   
27996       0       0       0       0       0       0       0       0       0   
27997       0       0       0       0       0       0       0       0       0   
27998       0       0       0       0       0       0       0       0       0   
27999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
27995       0  ...         0         0         0         0         0   
27996       0  ...         0         0         0         0         0   
27997       0  ...         0         0         0         0         0   
27998       0  ...         0         0         0         0         0   
27999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
27995         0         0         0         0         0  
27996         0         0         0         0         0  
27997         0         0         0         0         0  
27998         0         0         0         0         0  
27999         0         0         0         0         0  

[28000 rows x 784 columns]

## train data with SVM

Many training algorithms are sensitive to the order of the training instances, so it's generally good practice to shuffle them first:

In [7]:
np.random.seed(42)
rnd_idx = np.random.permutation(42000)
train_data = train_data.iloc[rnd_idx]
train_labels = train_labels.iloc[rnd_idx]

SVM requires StandardScaler

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_data_scaled = scaler.fit_transform(train_data.astype(np.float32))
test_data_scaled = scaler.transform(test_data.astype(np.float32))

Let's try an SVC with an RBF kernel (the default).

one vs rest

## find suitable hyperparameters

In [28]:
from sklearn.svm import SVC
svm_clf = SVC(decision_function_shape="ovr")
svm_clf.fit(train_data_scaled[:10000], train_labels[:10000])

SVC()

In [29]:
from sklearn.metrics import accuracy_score
train_labels_pred = svm_clf.predict(train_data_scaled)
accuracy_score(train_labels, train_labels_pred)

0.9502142857142857

That's promising, we get better performance even though we trained the model with less data. 

Let's tune the hyperparameters by doing a randomized search with cross validation. We will do this on a small dataset just to speed up the process:

In [30]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import reciprocal, uniform

param_distributions = {"gamma": reciprocal(0.001, 0.1), "C": uniform(1, 10)}
rnd_search_cv = RandomizedSearchCV(svm_clf, param_distributions, n_iter=10, verbose=2) #分为5份，验证5次
rnd_search_cv.fit(train_data_scaled[:1000], train_labels[:1000])

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] C=6.2790212507020655, gamma=0.04598195154931414 .................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .. C=6.2790212507020655, gamma=0.04598195154931414, total=   1.1s
[CV] C=6.2790212507020655, gamma=0.04598195154931414 .................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.0s remaining:    0.0s


[CV] .. C=6.2790212507020655, gamma=0.04598195154931414, total=   1.1s
[CV] C=6.2790212507020655, gamma=0.04598195154931414 .................
[CV] .. C=6.2790212507020655, gamma=0.04598195154931414, total=   1.3s
[CV] C=6.2790212507020655, gamma=0.04598195154931414 .................
[CV] .. C=6.2790212507020655, gamma=0.04598195154931414, total=   1.1s
[CV] C=6.2790212507020655, gamma=0.04598195154931414 .................
[CV] .. C=6.2790212507020655, gamma=0.04598195154931414, total=   1.1s
[CV] C=3.5078989500032103, gamma=0.008342102913200016 ................
[CV] . C=3.5078989500032103, gamma=0.008342102913200016, total=   1.1s
[CV] C=3.5078989500032103, gamma=0.008342102913200016 ................
[CV] . C=3.5078989500032103, gamma=0.008342102913200016, total=   1.1s
[CV] C=3.5078989500032103, gamma=0.008342102913200016 ................
[CV] . C=3.5078989500032103, gamma=0.008342102913200016, total=   1.1s
[CV] C=3.5078989500032103, gamma=0.008342102913200016 ................
[CV] .

[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:   53.7s finished


RandomizedSearchCV(estimator=SVC(),
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002BEDD440160>,
                                        'gamma': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000002BEDD440040>},
                   verbose=2)

In [31]:
rnd_search_cv.best_estimator_

SVC(C=8.534292122124205, gamma=0.0016254279892128252)

In [32]:
rnd_search_cv.best_score_

0.874

This looks pretty low but remember we only trained the model on 1,000 instances. Let's retrain the best estimator on the whole training set (run this at night, it will take hours):

In [33]:
rnd_search_cv.best_estimator_.fit(train_data_scaled, train_labels)

SVC(C=8.534292122124205, gamma=0.0016254279892128252)

In [34]:
train_labels_pred = rnd_search_cv.best_estimator_.predict(train_data_scaled)
accuracy_score(train_labels, train_labels_pred)

0.9994285714285714

**accuracy=0.96771**

not very good

## hyperparameters C=5 and gamma=0.005

Other people have found that the hyperparameters C=5 and gamma=0.005 yield even better performance (over 98% accuracy). By running the randomized search for longer and on a larger part of the training set, you may be able to find this as well.

In [12]:
from sklearn.svm import SVC
svm_clf = SVC(decision_function_shape="ovr",C=5,gamma=0.005)
svm_clf.fit(train_data_scaled, train_labels)

SVC(C=5, gamma=0.005)

In [13]:
from sklearn.metrics import accuracy_score
train_labels_pred = svm_clf.predict(train_data_scaled)
accuracy_score(train_labels, train_labels_pred)

0.9999761904761905

**accuracy=0.93835**

too bad

## use SVM model to predict labels of test set

In [14]:
test_labels_pred = svm_clf.predict(test_data_scaled)
test_labels_pred

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

## Model persistence using joblib

In [19]:
my_model =svm_clf

In [20]:
#save my_model
import joblib
#from sklearn.externals import joblib
joblib.dump(my_model, "my_model.pkl") # DIFF

['my_model.pkl']

In [ ]:
#load my_model
my_model_loaded = joblib.load("my_model.pkl") # DIFF

## export results

In [15]:
ImageId=np.arange(28001)[1:]
ImageId

array([    1,     2,     3, ..., 27998, 27999, 28000])

In [16]:
Label=test_labels_pred
Label

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [17]:
df=pd.DataFrame({'ImageId':ImageId,'Label':Label})
df

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      4
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [18]:
df.to_csv("SVM_submission.csv",index=False)

In [ ]:
'''
DataFrame.to_csv(path_or_buf=None, sep=', ', na_rep='', float_format=None, columns=None, header=True, index=True,
                 index_label=None, mode='w', encoding=None, compression=None, quoting=None, quotechar='"',
                 line_terminator='\n', chunksize=None, tupleize_cols=None, date_format=None, doublequote=True,
                 escapechar=None, decimal='.')
'''

参数：

path_or_buf : 文件路径，如果没有指定则将会直接返回字符串的 json

sep : 输出文件的字段分隔符，默认为 “,”

na_rep : 用于替换空数据的字符串，默认为''

float_format : 设置浮点数的格式（几位小数点）

columns : 要写的列

header : 是否保存列名，默认为 True ，保存

index : 是否保存索引，默认为 True ，保存

index_label : 索引的列标签名